USE [C:\USERS\NILS TERJE\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\DIVINGAPPGITHUB\DIVINGJOURNAL2\DIVINGJOURNAL2\APP_DATA\USERS.MDF]
GO

DECLARE	@return_value Int

EXEC	@return_value = [dbo].[Procedure]

SELECT	@return_value as 'Return Value'

GO
